import { getGenderAgeGroup } from '@/lib/sanityQueries';
import Footer from '../views/Footer';
import Navbar from '../views/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import { Providers, store } from '@/store';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let genderAgeGroupData = await getGenderAgeGroup();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Toaster position='top-right' />
          <div className='font-sora p-0 m-auto container '>
            <Navbar genderAgeGroupData={genderAgeGroupData} />
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
