import { getGenderAgeGroup } from '@/lib/sanityQueries';
import Footer from '../views/Footer';
import Navbar from '../views/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let genderAgeGroupData = await getGenderAgeGroup();
  console.log('genderAgeGroupData --->', genderAgeGroupData);
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='font-sora p-0 m-auto container '>
          <Navbar genderAgeGroupData={genderAgeGroupData} />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
